### ISSUE TITLE
Calendar timezones aren't correct.

### ISSUE THREAD

**Issue by tannewt** [adafruit/adafruit-circuitpython-weekly-meeting#4]
Looks like we may need to use VTIMEZONE: https://stackoverflow.com/questions/35645402/how-to-specify-timezone-in-ics-file-which-will-work-efficiently-with-google-outl

**Comment by jepler** [comment]
I'll investigate this if nobody else does first.

**Comment by jepler** [comment]
We fixed this, right?

**Comment by tannewt** [comment]
Yup! Works for me now.
